ingress:
  name: outfit-planner-ingress
  tls:
    - host: "*.outfitplanner.com"
      secretName: outfitplanner-tls
  rules:
    - host: "dashboard.outfitplanner.com"
      paths:
        - path: /remote/outfits
          backend:
            service:
              name: outfits
              port: 80
        - path: /remote/products
          backend:
            service:
              name: products
              port: 80
        - path: /api/products
          backend:
            service:
              name: product-service
              port: 8184
        - path: /api/outfits
          backend:
            service:
              name: outfit-service
              port: 8185
        - path: /
          backend:
            service:
              name: dashboard
              port: 8099
    - host: "keycloak-server.outfitplanner.com"
      paths:
        - path: /
          backend:
            service:
              name: keycloak-server
              port: 80
