image:
  repository: rzodkiewkowypotwor/integration-tests
  pullPolicy: IfNotPresent
container:
  env:
    - key: REMOTE_URL
      value: http://selenium-chrome-service.default.svc.cluster.local:4444/wd/hub
    - key: APP_URL
      value: http://dashboard
initContainer:
  name: init-wait-for-dashboard
  image: busybox
  command: [ 'sh', '-c', 'until nslookup dashboard.default.svc.cluster.local; do echo waiting for dashboard; sleep 2; done;' ]