image:
  repository: rzodkiewkowypotwor/integration-tests
  pullPolicy: IfNotPresent
container:
  env:
    - key: REMOTE_URL
      value: http://selenium-chrome-service.default.svc.cluster.local:4444/wd/hub
    - key: APP_URL
      value: http://dashboard
    - key: KEYCLOAK_URL
      value: http://keycloak-server
    - key: PRODUCT_SERVICE_URL
      value: http://product-service:8184
    - key: PRODUCTS_APP_URL
      value: http://products
initContainer:
  name: init-wait-for-dashboard
  image: busybox
  command: [ 'sh', '-c', 'until nslookup keycloak-server.default.svc.cluster.local && wget -q -O /dev/null http://keycloak-server.default.svc.cluster.local/realms/outfitplanner-realm && nslookup product-service.default.svc.cluster.local; do echo waiting for keycloak-server and products; sleep 2; done; sleep 10;' ]