app:
  name: keycloak-server
  replicaCount: 1
  container:
    image: rzodkiewkowypotwor/keycloak-server
    tag: {{ .Values.global.commitSha | default "0.0.2" }}
    port: 8080
    args: [ "start-dev", "--import-realm", "--http-port=8080", "--https-port=443" ]
    env:
      - key: name
        value: value
      - key: KEYCLOAK_LOGLEVEL
        value: DEBUG
      - key: JAVA_OPTS
        value: "-Djboss.http.port=8082"
      - key: DB_VENDOR
        value: POSTGRES
      - key: DB_ADDR
        value: postgres_keycloak
      - key: DB_DATABASE
        value: keycloak
      - key: DB_USER
        value: keycloak
      - key: DB_SCHEMA
        value: public
      - key: DB_PASSWORD
        value: keycloak
      - key: KEYCLOAK_IMPORT
        value: /tmp/outfit-planner-config.json
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      - key: KC_PROXY
        value: edge
  service:
    port: 80
    type: ClusterIP