app:
  name: keycloak-server
  replicaCount: 1
  container:
    image: rzodkiewkowypotwor/keycloak-server:0.0.2
    port: 8080
    args: [ "start-dev", "--import-realm", "--http-port=8080", "--https-port=443" ]
    env:
      - key: name
        value: value
      - key: KEYCLOAK_LOGLEVEL
        value: DEBUG
      - key: JAVA_OPTS
        value: "-Djboss.http.port=8082"
      - key: DB_VENDOR
        value: POSTGRES
      - key: DB_ADDR
        value: postgres_keycloak
      - key: DB_DATABASE
        value: keycloak
      - key: DB_USER
        value: keycloak
      - key: DB_SCHEMA
        value: public
      - key: DB_PASSWORD
        value: keycloak
      - key: KEYCLOAK_IMPORT
        value: /tmp/outfit-planner-config.json
      - key: KC_HTTPS_CERTIFICATE_FILE
        value: /opt/keycloak/conf/keycloak-server.crt
      - key: KC_HTTPS_CERTIFICATE_KEY_FILE
        value: /opt/keycloak/conf/keycloak-server.key
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      #      - key: KC_HEALTH_ENABLED
      #        value: "true"
#      - key: KC_HOSTNAME
#        value: keycloak-server
      - key: KC_PROXY
        value: edge
  volume:
    secret: true
    volumeName: keycloak-certs
    mountPath: /opt/keycloak/conf
  #    volumeMount:
  #      - name: keycloak-certs
  #        mountPath: /opt/keycloak/conf
  #    config:
  #      - name: keycloak-server-config-map
  #  volumes:
  #    - name: keycloak-certs
  #      secret:
  #        secretName: keycloak-certs
  service:
    port: 80
    type: LoadBalancer
  config:
    enabled: false
    name: keycloak-server-config-map
    data:
      - key: KEYCLOAK_LOGLEVEL
        value: DEBUG
      - key: JAVA_OPTS
        value: "-Djboss.http.port=8082"
      - key: DB_VENDOR
        value: POSTGRES
      - key: DB_ADDR
        value: postgres_keycloak
      - key: DB_DATABASE
        value: keycloak
      - key: DB_USER
        value: keycloak
      - key: DB_SCHEMA
        value: public
      - key: DB_PASSWORD
        value: keycloak
      - key: KEYCLOAK_IMPORT
        value: /tmp/outfit-planner-config.json
      - key: KC_HTTPS_CERTIFICATE_FILE
        value: /opt/keycloak/conf/keycloak-server.crt
      - key: KC_HTTPS_CERTIFICATE_KEY_FILE
        value: /opt/keycloak/conf/keycloak-server.key
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      - key: KC_HEALTH_ENABLED
        value: \"true\"
      - key: KC_HOSTNAME
        value: keycloak-server
      - key: KC_PROXY
        value: edge
#  volumes:
#    - name: dashboard-certs
#      secret:
#        name: dashboard-certs
#      mountPath: /etc/nginx/certs