app:
  name: outfits
  replicaCount: 1
  container:
    image: rzodkiewkowypotwor/outfits-frontend
    tag: ${ENV_COMMIT_SHA:-1.0.3-SNAPSHOT}
    port: 80
    env:
#      - key: VIRTUAL_HOST
#        value: outfits
      - key: NGINX_ENVSUBST_OUTPUT_DIR
        value: /etc/nginx
      - key: OUTFITS_HOST
        value: http://outfits.outfitplanner.com
      - key: PRODUCTS_HOST
        value: http://products.outfitplanner.com
  service:
    port: 80
    type: ClusterIP
