version: '3.7'

services:

  products-proxy:
    restart: always
    hostname: products
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-build
      args:
        APP_NAME: products
    expose:
      - 80
    environment:
      VIRTUAL_HOST: products.outfitplanner.com
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      VIRTUAL_PATH: /
      OUTFITS_HOST: http://outfits
      PRODUCTS_HOST: http://products
    networks:
      - ${GLOBAL_NETWORK}

  outfits-proxy:
    restart: always
    hostname: outfits
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-build
      args:
        APP_NAME: outfits
    expose:
      - 80
    environment:
      VIRTUAL_HOST: outfits.outfitplanner.com
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      VIRTUAL_PATH: /
      OUTFITS_HOST: http://outfits
      PRODUCTS_HOST: http://products
    networks:
      - ${GLOBAL_NETWORK}

  dashboard-proxy:
    restart: always
    hostname: ${DASHBOARD_HOST:-dashboard}
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-build
      args:
        APP_NAME: dashboard
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${DASHBOARD_HOST:-dashboard}
      VIRTUAL_PATH: /
      OUTFITS_HOST: http://outfits
      PRODUCTS_HOST: http://products
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    networks:
      - ${GLOBAL_NETWORK}
