version: '3.7'

volumes:
  frontend-app:
    driver_opts:
      type: none
      device: ${OUTFIT_PLANNER_MF_PATH}/apps
      o: bind
  libs:
    driver_opts:
      type: none
      device: ${OUTFIT_PLANNER_MF_PATH}/libs
      o: bind

services:

  products-app:
    hostname: products-development
    ports:
      - "4201:4200"
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-serve
    environment:
      APP_NAME: products
      VIRTUAL_HOST: products.outfitplanner.com
      VIRTUAL_PATH: /
    volumes:
      - frontend-app:/app/apps
      - libs:/app/libs
    networks:
      - outfit-planner-system
    expose:
      - 4200
#
  outfits-app:
    hostname: outfits-development
    ports:
      - "4202:4200"
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-serve
    environment:
      APP_NAME: outfits
      VIRTUAL_HOST: outfits.outfitplanner.com
      VIRTUAL_PATH: /
    volumes:
      - frontend-app:/app/apps
      - libs:/app/libs
    networks:
      - ${GLOBAL_NETWORK}
    expose:
      - 4200

  dashboard-app:
    hostname: dashboard-development
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-serve
    ports:
      - "4203:4200"
    environment:
      APP_NAME: dashboard
      VIRTUAL_HOST: ${DASHBOARD_HOST}
      VIRTUAL_PATH: /
    volumes:
      - frontend-app:/app/apps
      - libs:/app/libs
    networks:
      - ${GLOBAL_NETWORK}
    expose:
      - 4200