version: '3.7'

volumes:
  frontend-app:
    driver_opts:
      type: none
      device: ${OUTFIT_PLANNER_MF_PATH}
      o: bind

services:

  products-app:
    hostname: products-development
    ports:
      - "4201:4201"
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-serve
    environment:
      APP_NAME: products
      VIRTUAL_HOST: products-dev
      VIRTUAL_PORT: 4201
#      HTTPS_METHOD: redirect
#      VIRTUAL_PROTO: https
    volumes:
      - frontend-app:/app
    networks:
      - outfit-planner-system
    expose:
#      - 80
      - 4201
#
  outfits-app:
    hostname: outfits-development
    ports:
      - "4202:4202"
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-serve
    environment:
      APP_NAME: outfits
      VIRTUAL_HOST: outfits-dev
      VIRTUAL_PORT: 4202
#      HTTPS_METHOD: redirect
#      VIRTUAL_PROTO: https
    volumes:
      - frontend-app:/app
    networks:
      - ${GLOBAL_NETWORK}
    expose:
#      - 80
      - 4202
#
  dashboard-app:
    hostname: dashboard-development
    build:
      context: ../../../outfit-planner-mf
      dockerfile: Dockerfile-serve
    environment:
      APP_NAME: dashboard
      VIRTUAL_HOST: dashboard-dev
      VIRTUAL_PORT: 4200
      VIRTUAL_PATH: /
    volumes:
      - frontend-app:/app
    networks:
      - ${GLOBAL_NETWORK}
    expose:
#      - 80
      - 4200