version: '3.7'


services:
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_SOCK_PATH}:/tmp/docker.sock:ro
      - ${CERTS_PATH}:/etc/nginx/certs
      - ${OUTFIT_PLANNER_SYSTEM_PATH}/infrastructure/docker/proxy.conf:/etc/nginx/proxy.conf
    networks:
      - ${GLOBAL_NETWORK}




