version: '3.7'

networks:
  outfit-planner_outfit-planner-system:
    external: true

services:

  integrations-app:
    build:
      context: ../../integration-tests
      dockerfile: Dockerfile
    environment:
      APP_URL: http://dashboard.outfitplanner.com
      REMOTE_URL: http://selenium-chrome:4444/wd/hub
      KEYCLOAK_URL: http://keycloak-server.outfitplanner.com:8082
    networks:
      - outfit-planner_outfit-planner-system

  selenium-chrome:
    hostname: selenium-chrome
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    networks:
      - outfit-planner_outfit-planner-system