FROM node:16-alpine3.12 as build

ARG APP_NAME

WORKDIR /app

COPY . .
#COPY ./package.json .

RUN npm install -g @angular/cli
RUN npm install -g nx

RUN npm install
RUN nx build ${APP_NAME}

FROM nginx:1.21-alpine
ARG APP_NAME

#COPY prod-proxy/nginx.conf /etc/nginx/templates/nginx.conf.template


WORKDIR /app
COPY --from=build /app/dist/apps/${APP_NAME} /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/templates/nginx.conf.template


EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
