FROM node:22-alpine3.19 as build
ARG APP_NAME

WORKDIR /app
COPY package*.json ./

RUN npm install --production

COPY . .

RUN npm exec nx build ${APP_NAME}


FROM nginx:1.27-alpine
ARG APP_NAME

WORKDIR /app
COPY --from=build /app/dist/apps/${APP_NAME} /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/templates/nginx.conf.template

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
