apiVersion: v1
kind: Service
metadata:
  name: integration-tests-service
spec:
  selector:
    app: integration-tests
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}