apiVersion: v1
kind: Service
metadata:
  name: prediction-service-service
spec:
  selector:
    app: prediction-service
  ports:
    - protocol: TCP
      port: 2006
      targetPort: 2006
  type: LoadBalancer