ingress:
  name: outfit-planner-ingress
  clusterIssuer: letsencrypt-prod
  tls:
    - hosts:
        - dashboard.outfitplanner.cloud
        - keycloak-server.outfitplanner.cloud
        - outfits.outfitplanner.cloud
        - products.outfitplanner.cloud
  rules:
    - host: "dashboard.outfitplanner.cloud"
      paths:
        - path: /api/products
          backend:
            service:
              name: product-service
              port: 8184
        - path: /api/outfits
          backend:
            service:
              name: outfit-service
              port: 8185
        - path: /
          backend:
            service:
              name: dashboard
              port: 8099
    - host: "keycloak-server.outfitplanner.cloud"
      paths:
        - path: /
          backend:
            service:
              name: keycloak-server
              port: 80
    - host: "products.outfitplanner.cloud"
      paths:
        - path: /
          backend:
            service:
              name: products
              port: 80
    - host: "outfits.outfitplanner.cloud"
      paths:
        - path: /
          backend:
            service:
              name: outfits
              port: 80
