name: integration-tests
replicaCount: 1
image:
  repository: rzodkiewkowypotwor/integration-tests
  tag: tag
  pullPolicy: IfNotPresent
service:
  port: 80
  type: ClusterIP
container:
  env:
    - key: empty
      value: empty