apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak-service
spec:
  selector:
    app: postgres-keycloak
  ports:
    - protocol: TCP
      port: 5439
      targetPort: 5432
  type: LoadBalancer