apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-server
  template:
    metadata:
      labels:
        app: keycloak-server
    spec:
      volumes:
        - name: keycloak-certs
          secret:
            secretName: keycloak-certs
      containers:
        - name: keycloak-server-container
          image: rzodkiewkowypotwor/keycloak-server:0.0.1
          args: ["start-dev", "--import-realm", "--http-port", "8082", "--https-port", "8443"]
          ports:
            - containerPort: 8443
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: keycloak-server-config-map
          volumeMounts:
            - name: keycloak-certs
              mountPath: /opt/keycloak/conf