apiVersion: v1
kind: Service
metadata:
  name: keycloak-server-service
spec:
  selector:
    app: keycloak-server
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 443
  type: LoadBalancer