{{- if and .Values.secretName .Values.certFileName .Values.keyFileName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  {{- $certContent := .Files.Get (printf "files/%s" .Values.certFileName) | b64enc }}
  {{- $keyContent := .Files.Get (printf "files/%s" .Values.keyFileName) | b64enc }}
  {{ .Values.certFileName | quote }}: {{ $certContent | quote }}
  {{ .Values.keyFileName | quote }}: {{ $keyContent | quote }}
{{- end }}