apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-service
spec:
  selector:
    app: selenium-chrome
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 4444
  type: {{ .Values.service.type }}