helmDefaults:
  kubeContext: kubernetes-admin@outfitplanner-cluster

repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: default
    chart: jetstack/cert-manager
    version: v1.14.5
    values:
      - ./values/cert-manager.yaml
    set:
      - name: installCRDs
        value: true

  - name: cert-manager-issuer
    namespace: default
    chart: ./charts/issuer-chart
    version: v0.1.0
    installed: true
    disableValidation: true
    needs:
      - default/cert-manager
    values:
      - letsEncryptClusterIssuer:
          email: preferujeanalny@gmail.com

  - name: prediction-service
    chart: ./charts/app
    values:
      - ./values/prediction-service.yaml

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.10.0
    wait: true
    values:
      - controller:
          service:
            externalIPs:
              - "146.59.116.67"

  - name: product-postgres
    chart: ./charts/app
    values:
      - ./values/product-postgres.yaml

  - name: outfits-service
    chart: ./charts/app
    values:
      - ./values/outfits-service.yaml

  - name: product-service
    chart: ./charts/app
    values:
      - ./values/product-service.yaml

  - name: dashboard
    chart: ./charts/app
    values:
      - ./values/dashboard.yaml

  - name: outfits
    chart: ./charts/app
    values:
      - ./values/outfits.yaml

  - name: products
    chart: ./charts/app
    values:
      - ./values/products.yaml

  - name: schema-registry
    chart: ./charts/app
    values:
      - ./values/schema-registry.yaml

  - name: zookeeper
    chart: ./charts/app
    values:
      - ./values/zookeeper.yaml

  - name: kafka-broker
    chart: ./charts/app
    values:
      - ./values/kafka-broker.yaml

  - name: keycloak-postgres
    chart: ./charts/app
    values:
      - ./values/keycloak-postgres.yaml

  - name: keycloak-server
    chart: ./charts/app
    values:
      - ./values/keycloak-server.yaml

  - name: my-mongodb-release
    namespace: default
    chart: bitnami/mongodb
    version: 15.1.5
    values:
      - ./values/outfits-mongodb.yaml

  - name: ingress-controller
    chart: ./charts/ingress
    set:
      - name: ingressClassResource.default
        value: "true"
    values:
      - ./values/ingress.yaml
