#helmDefaults:
#  kubeContext: minikube

#environments:
#  test:
#    values:
#      - ./env/test.yaml
#  prod:
#    values:
#      - ./env/prod.yaml

repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: outfitplanner-repo
    url: https://cwianek.github.io/outfit-planner

releases:

  - name: outfitplanner-tls
    chart: ./charts/secrets
    values:
      - ./values/outfitplanner-tls.yaml

  - name: prediction-service
    chart: outfitplanner-repo/app
    values:
      - ./values/global-values.yaml
      - ./values/prediction-service.yaml

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.9.1

  - name: product-postgres
    chart: ./charts/app
    values:
      - ./values/product-postgres.yaml

  - name: outfits-service
    chart: ./charts/app
    values:
      - ./values/global-values.yaml
      - ./values/outfits-service.yaml

  - name: product-service
    chart: ./charts/app
    values:
      - ./values/global-values.yaml
      - ./values/product-service.yaml

  - name: dashboard
    chart: ./charts/app
    values:
      - ./values/global-values.yaml
      - ./values/dashboard.yaml

  - name: outfits
    chart: ./charts/app
    values:
      - ./values/global-values.yaml
      - ./values/outfits.yaml

  - name: products
    chart: ./charts/app
    values:
      - ./values/global-values.yaml
      - ./values/products.yaml

  - name: schema-registry
    chart: ./charts/app
    values:
      - ./values/schema-registry.yaml

  - name: zookeeper
    chart: ./charts/app
    values:
      - ./values/zookeeper.yaml

  - name: kafka-broker
    chart: ./charts/app
    values:
      - ./values/kafka-broker.yaml

  - name: keycloak-postgres
    chart: ./charts/app
    values:
      - ./values/keycloak-postgres.yaml

  - name: keycloak-server
    chart: ./charts/app
    values:
      - ./values/global-values.yaml
      - ./values/keycloak-server.yaml

  - name: my-mongodb-release
    namespace: default
    chart: bitnami/mongodb
    version: 14.7.0
    values:
      - ./values/outfits-mongodb.yaml

  - name: ingress-controller
    chart: ./charts/ingress
    set:
      - name: ingressClassResource.default
        value: "true"
    values:
      - ./values/ingress.yaml

  - name: selenium-chrome
    chart: ./charts/selenium-chrome

  - name: integration-tests
    chart: ./charts/integration-tests
    values:
      - ./values/global-values.yaml
      - ./values/integration-tests.yaml
