repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:

  - name: dashboard-tls
    chart: ./charts/secrets
    values:
      - ./values/dashboard-tls.yaml

  - name: outfits-tls
    chart: ./charts/secrets
    values:
      - ./values/outfits-tls.yaml

  - name: products-tls
    chart: ./charts/secrets
    values:
      - ./values/products-tls.yaml

  - name: keycloak-tls
    chart: ./charts/secrets
    values:
      - ./values/keycloak-server-tls.yaml

  - name: keycloak-certs
    chart: ./charts/secrets
    values:
      - ./values/keycloak-certs.yaml

  - name: prediction-service
    chart: ./charts/app
    values:
      - ./values/prediction-service.yaml

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.8.4

  - name: product-postgres
    chart: ./charts/app
    values:
      - ./values/product-postgres.yaml

  - name: outfits-service
    chart: ./charts/app
    values:
      - ./values/outfits-service.yaml

  - name: product-service
    chart: ./charts/app
    values:
      - ./values/product-service.yaml

  - name: dashboard
    chart: ./charts/app
    values:
      - ./values/dashboard.yaml

  - name: outfits
    chart: ./charts/app
    values:
      - ./values/outfits.yaml

  - name: products
    chart: ./charts/app
    values:
      - ./values/products.yaml

  - name: schema-registry
    chart: ./charts/app
    values:
      - ./values/schema-registry.yaml

  - name: zookeeper
    chart: ./charts/app
    values:
      - ./values/zookeeper.yaml

  - name: kafka-broker
    chart: ./charts/app
    values:
      - ./values/kafka-broker.yaml

  - name: keycloak-postgres
    chart: ./charts/app
    values:
      - ./values/keycloak-postgres.yaml

  - name: keycloak-server
    chart: ./charts/app
    values:
      - ./values/keycloak-server.yaml

  - name: my-mongodb-release
    namespace: default
    chart: bitnami/mongodb
    version: 14.4.2
    values:
      - ./values/outfits-mongodb.yaml

  - name: ingress-controller
    chart: ./charts/ingress
    set:
      - name: ingressClassResource.default
        value: "true"
    values:
      - ./values/ingress.yaml