name: Build and push keycloak-server docker image

#on:
#  push:
#    paths:
#      - 'outfit-planner-system/infrastructure/docker/keycloak/.version'
#  pull_request:
#    branches:
#      - master
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read version from file
        id: version
        run: echo "::set-output name=version::$(cat outfit-planner-system/infrastructure/docker/keycloak/.version)"

      - name: Build and push Docker image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
          TAG="latest"
          else
          # Extract branch name from GitHub context
          TAG=$(echo "${{ github.sha }}")
          fi
          
          docker build -t rzodkiewkowypotwor/keycloak-server:${TAG} \
          -f outfit-planner-system/infrastructure/docker/keycloak/Dockerfile outfit-planner-system/infrastructure/docker/keycloak/.
          docker push rzodkiewkowypotwor/keycloak-server:${TAG}