name: Lint and Test Charts

on:
  push:
    paths:
      - '.github/workflows/kubernetes-tests.yml'

jobs:
  Test-on-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.6.0'  # Specify the desired Helm version

      - name : Preparing cluster for kube-ez
        run: |
          cd $GITHUB_WORKSPACE/outfit-planner-system/infrastructure/kubernetes
          helmfile --file helmfile.yaml lint
          helmfile --file helmfile.yaml apply

#      - name: Deploying all releases with Helmfile
#        run: |
#          cd $GITHUB_WORKSPACE/outfit-planner-system/infrastructure/kubernetes
#          helmfile --file helmfile.yaml apply

      - name: Ensure the cluster is up and running
        run: |
          kubectl cluster-info
          kubectl get nodes