name: Lint and Test Charts

on:
  push:
    paths:
      - '.github/workflows/kubernetes-tests.yml'

jobs:
  Test-on-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ## starts the cluster
      - name: Testing on a k8s Kind Cluster
        uses: helm/kind-action@v1.4.0


      - name: Install Helmfile
        run: |
          wget https://github.com/helmfile/helmfile/releases/download/v0.161.0/helmfile_0.161.0_linux_amd64.tar.gz -O /tmp/helmfile.tar.gz
          tar -xzf /tmp/helmfile.tar.gz -C /usr/local/bin/
          chmod +x /usr/local/bin/helmfile

      - name: Install helm-diff plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff

      ## makes sure cluster is up and running
      - run: |
          kubectl cluster-info
          kubectl get nodes

      - name : Preparing cluster for kube-ez
        run: |
          cd $GITHUB_WORKSPACE/outfit-planner-system/infrastructure/kubernetes
          helmfile --file helmfile.yaml apply


      - name: Wait for Pods to be Running
        run: |
          kubectl wait --for=condition=Ready pod --all --timeout=300s

      - name: Print Events for All Pods
        run: |
          kubectl get pods --all-namespaces -o json | jq -r '.items[] | "\(.metadata.namespace)/\(.metadata.name)"' | xargs -I {} kubectl get events --namespace={} --sort-by=.metadata.creationTimestamp

      - name: Print Logs for All Pods
        run: |
          kubectl get pods --all-namespaces -o json | jq -r '.items[] | "\(.metadata.namespace)/\(.metadata.name)"' | xargs -I {} kubectl logs --namespace={} {}