name: Build and push outfit-service to Docker Hub

on:
  push:
    paths:
      - 'outfit-planner-system/outfit-service/**'
      - '.github/workflows/outfit-service-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build artifacts
        env:
          FILE_PATH: /outfit-planner-system/pom.xml
        run: |
          cd $GITHUB_WORKSPACE/outfit-planner-system
          # Replace this with your build command
          mvn install -Dmaven.test.skip=true -Dfile.path=${FILE_PATH}
          cp outfit-service/target/*.war artifact.war

      - name: List artifacts before upload
        run: |
          ls -R

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outfit-planner-wars
          path: |
            outfit-planner-system/artifact.war


  docker:
    runs-on: ubuntu-latest

    needs: build  # Ensure the 'build' job completes before starting this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: outfit-planner-wars
          path: outfit-planner-system/infrastructure/docker/backend-service  # Adjust the path based on your build output

      - name: List downloaded files
        run: |
          ls -R outfit-planner-system/infrastructure/docker/backend-service

      - name: Build Docker image
        run: |
          set -x
          # Replace this with your Docker build command
          docker build -t rzodkiewkowypotwor/outfit-service:1.0.8-SNAPSHOT -f outfit-planner-system/infrastructure/docker/backend-service/Dockerfile outfit-planner-system/infrastructure/docker/backend-service/.
          set +x

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          # Replace this with your Docker push command
          docker push rzodkiewkowypotwor/outfit-service:1.0.8-SNAPSHOT
