name: Build and push outfit-service to Docker Hub

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build artifacts
        env:
          FILE_PATH: /outfit-planner-system/pom.xml
        run: |
          cd $GITHUB_WORKSPACE/outfit-planner-system
          # Replace this with your build command
          mvn install -Dmaven.test.skip=true -Dfile.path=${FILE_PATH}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: outfit-planner-wars
          path: |
            **/*.war



  docker:
    runs-on: ubuntu-latest

    needs: build  # Ensure the 'build' job completes before starting this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: outfit-planner-wars
          path: .github/workflows/  # Adjust the path based on your build output

      - name: Build Docker image
        run: |
          # Replace this with your Docker build command
          docker build -t com.outfit.planner.system/outfit-service:1.0-SNAPSHOT -f .github/workflows/Dockerfile .github/workflows/.

      - name: Push Docker image
        run: |
          # Replace this with your Docker push command
          docker push com.outfit.planner.system/outfit-service:1.0-SNAPSHOT
