name: Build and push outfits-frontend docker image

on:
  push:
    paths:
      - 'outfit-planner-system/outfit-planner-mf/outfits/**'
      - '.github/workflows/outfit-frontend-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        run: |
          docker build -t rzodkiewkowypotwor/outfits-frontend:1.0.3-SNAPSHOT \
          --build-arg APP_NAME=outfits \
          -f outfit-planner-mf/Dockerfile-build outfit-planner-mf/.
          docker push rzodkiewkowypotwor/outfits-frontend:1.0.3-SNAPSHOT